# Generated by Django 3.1.7 on 2021-03-12 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='priopity',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='priopity',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='priopity',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
