# Generated by Django 3.1.7 on 2021-03-13 16:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210312_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1260)),
                ('priopity', models.PositiveIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(100.0)])),
                ('likes', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
            bases=(post.models.LikeMixin, models.Model),
        ),
    ]
